version: '2'
services:
    cmp-app:
        image: cmp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cmp-mysql:3306/cmp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cmp-elasticsearch:9300
        ports:
            - 8080:8080
    cmp-mysql:
        extends:
            file: mysql.yml
            service: cmp-mysql
    cmp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cmp-elasticsearch
